### ISSUE TITLE
What are all the addresses in abi.js?

### ISSUE THREAD

**Issue by Borkuz** [0xherman/dxsale#2]
`var n = "0x7163DF5c2a7D28F067B71a0505372e55f51E7358"
          , d = "0xc9904012e42C3613d181D0827Dcb3F7FD3205822"
          , c = "0xC7065e692D2caCF7173C7BC08c6849eb9Ef48b38"
          , i = "0x58C38bF08BD023824ABD05Db9a4e4CAb991E447C"
          , b = "0x1C8aB27b538b5e43c151460cBc6D271cB9EeE4aF"
          , f = "0x9c55c9E02295B3E8C00501358E8289afc8b39edF"
          , s = "0xc5fE280422117461af9b953Da413e9627E3b9a40"
          , p = "0x9c55c9E02295B3E8C00501358E8289afc8b39edF"
          , u = "0x67491cFbbD29DEAA1a05F952Bc069CdAA5919711"
          , C = "0x3F051B8ba7AD8CCBff909b9F8d5D5fe967B9F6fe"
          , F = "0xd5F1593D585cbAC2d5bCae2dbae4fc159375C6dD"
          , B = "0x19641A259afAF9Bc92Ee02C2BA4c672a80B931B6"
          , D = "0xcd5fD649Da9E0563BbbdD555ab6006Dc9a596b49"
          , E = ""
          , A = "0xcd5fD649Da9E0563BbbdD555ab6006Dc9a596b49"
          , y = ""
          , x `

**Comment by 0xherman** [comment]
I think I copied whole thing from dxsale website and wasn't sure which was the actual address
